apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: backend-imagefilter
  name: backend-imagefilter
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-imagefilter
    spec:
      containers:
      - image: chrillen/udacity-restapi-imagefilter
        name: backend-imagefilter
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                  
        env:
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: JWT_SECRET
      restartPolicy: Always      