apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-imagefilter
  name: backend-imagefilter
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    service: backend-imagefilter